In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
diabetes = pd.read_csv('diabetes_prevalence.csv')
food = pd.read_csv('food_access.csv')

In [3]:
diabetes.head()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
1670575,2018,SC,South Carolina,Abbeville,45001,45001950200,BRFSS,Prevention,"Fecal occult blood test, sigmoidoscopy, or col...",%,...,NaN,66.2,69.4,"4,195",POINT (-82.4112413 34.32675092),45001950200,PREVENT,COLON_SCREEN,CrdPrv,Colorectal Cancer Screening
1658454,2019,SC,South Carolina,Abbeville,45001,45001950100,BRFSS,Health Outcomes,Current asthma among adults aged >=18 years,%,...,NaN,9.7,10.3,"3,254",POINT (-82.33436263 34.411938),45001950100,HLTHOUT,CASTHMA,CrdPrv,Current Asthma
1658527,2018,SC,South Carolina,Abbeville,45001,45001950400,BRFSS,Health Risk Behaviors,Sleeping less than 7 hours among adults aged >...,%,...,NaN,41.0,43.0,"6,073",POINT (-82.36863107 34.2212182),45001950400,RISKBEH,SLEEP,CrdPrv,Sleep <7 hours
1658535,2019,SC,South Carolina,Abbeville,45001,45001950600,BRFSS,Health Outcomes,Coronary heart disease among adults aged >=18 ...,%,...,NaN,9.0,9.9,"3,064",POINT (-82.58885683 34.13199348),45001950600,HLTHOUT,CHD,CrdPrv,Coronary Heart Disease
1666439,2018,SC,South Carolina,Abbeville,45001,45001950200,BRFSS,Prevention,Cervical cancer screening among adult women ag...,%,...,NaN,81.6,84.6,"4,195",POINT (-82.4112413 34.32675092),45001950200,PREVENT,CERVICAL,CrdPrv,Cervical Cancer Screening

In [4]:
food.head()

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga County,1,1912,693,0,0.0,0.00,0,...,221.0,1622.0,217.0,14.0,0.0,14.0,45.0,44.0,6.0,102.0
1,1001020200,Alabama,Autauga County,1,2170,743,0,181.0,8.34,1,...,214.0,888.0,1217.0,5.0,0.0,5.0,55.0,75.0,89.0,156.0
2,1001020300,Alabama,Autauga County,1,3373,1256,0,0.0,0.00,0,...,439.0,2576.0,647.0,17.0,5.0,11.0,117.0,87.0,99.0,172.0
3,1001020400,Alabama,Autauga County,1,4386,1722,0,0.0,0.00,0,...,904.0,4086.0,193.0,18.0,4.0,11.0,74.0,85.0,21.0,98.0
4,1001020500,Alabama,Autauga County,1,10766,4082,0,181.0,1.68,0,...,1126.0,8666.0,1437.0,296.0,9.0,48.0,310.0,355.0,230.0,339.0

In [5]:
diabetes = diabetes[diabetes['Measure'].str.contains('diabetes')]
diabetes = diabetes[['LocationName', 'Data_Value']]
diabetes.head()

    LocationName  Data_Value
11   23025966600        12.2
13   23031034002         8.7
50   23025965600        12.8
67    1083020300        10.6
72    1087231900        18.1

In [18]:
food = food[['CensusTract', 'State', 'County', 'LATracts_half', 'LATracts1', 'LATracts10', 'LATracts20', 'Pop2010', 'Urban', 'PCTGQTRS', 'PovertyRate', 'MedianFamilyIncome', 'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian', 'TractNHOPI', 'TractAIAN', 'TractHispanic', 'TractHUNV']]
food[food['Pop2010'] < 1000]['Pop2010'].count()

np.int64(777)

In [15]:
df = diabetes.merge(food, left_on = 'LocationName', right_on = 'CensusTract', how = 'inner')
df.isnull().sum()

LocationName            0
Data_Value              0
CensusTract             0
State                   0
County                  0
LATracts_half           0
LATracts1               0
LATracts10              0
LATracts20              0
Pop2010                 0
Urban                   0
PCTGQTRS               24
PovertyRate             3
MedianFamilyIncome    545
TractSeniors            4
TractWhite              4
TractBlack              4
TractAsian              4
TractNHOPI              4
TractAIAN               4
TractHispanic           4
TractHUNV               4
dtype: int64

In [ ]:
print(diabetes.shape)
print(food.shape)